#!/bin/bash

while getopts "v:h" OPTION; do
    case $OPTION in
    v)
        version=$OPTARG
        echo "version $version"
        ;;
    h)
        echo "Usage $(basename $BASH_SOURCE) -v version_number or just $(basename $BASH_SOURCE) for the latest available"
        ;;
    \?)
        echo "Incorrect options provided"
        exit 1
        ;;
    esac
done

if [ $OPTIND -eq 1 ];
 then
   wget -q http://www.phpmyadmin.net/home_page/version.php -O /tmp/phpmyadmin.tmp
   currentversion=`head -n 1 /tmp/phpmyadmin.tmp`
   version=$currentversion
fi


dlink="https://files.phpmyadmin.net/phpMyAdmin/$version/phpMyAdmin-$version-all-languages.tar.gz"


cd /usr/local/webapps/
rm -rf phpMyAdmin4
curl -O $dlink
tar -zxvf phpMyAdmin-$currentversion-all-languages.tar.gz
cd phpMyAdmin-$currentversion-all-languages
cp ../phpMyAdmin/config.inc.php .  
cd ../ 
mv phpMyAdmin phpMyAdmin4
mv phpMyAdmin-$currentversion-all-languages phpMyAdmin
rm -rf phpMyAdmin-$currentversion-all-languages.tar.gz

rm -rf /tmp/phpmyadmin.tmp
